### 
POST http://localhost:3001/user
Content-Type: application/json

{
   "login":  "ISOGRAF",
   "password":  "Admin"
}

###       
GET http://localhost:3001/matot/502974
Content-Type: application/json

 
###  
POST http://localhost:3001/movot
Content-Type: application/json

{
   "ImaPro":  356,
   "ImaDes1": "Despacho",
   "ImaAnc":  0,
   "ImaLar":  0,
   "ImaSel":  "S",
   "ImaCan":  1.00,
   "ImaPun":  114.00,
   "ImaSer":  "503079"

}

###  
POST http://localhost:3001/occom
Content-Type: application/json

{
   "Enlace":  "2024-03005",
   "IocCod":  "2024-03005",
   "IocTip":  "S",
   "IocPro":  "6",
   "IocDes":  "ARMADO BOLSA 02 PIEZAS",
   "IocCan":  1,
   "IocPun":  600.00,
   "Ioctot":  600.00,
   "IocOp":  "503021"

}


###
GET http://localhost:3001/realot/502974
Content-Type: application/application/json


###
POST  http://localhost:3001/generarpdf
Content-Type: application/pdf

###
GET http://localhost:3001/matot/product/?id=503079


###
PATCH http://localhost:3001/movot/update/_96lmciwovbe?cant=3&pu=9.2
Content-Type: application/json


###
PATCH  http://localhost:3001/movot/updateser/2024-03013001?fact=FAC0001
Content-Type: application/json